name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'formula1_service/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'formula1_service/**'
      - '.github/workflows/backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: f1
          POSTGRES_PASSWORD: f1
          POSTGRES_DB: f1_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: formula1_service/package-lock.json

    - name: Install Dependencies
      working-directory: ./formula1_service
      run: npm ci

    - name: Run Tests
      working-directory: ./formula1_service
      env:
        NODE_ENV: test
        DB_HOST: localhost
        DB_PORT: 5432
        DB_USERNAME: f1
        DB_PASSWORD: f1
        DB_DATABASE: f1_test
      run: npm run test

    - name: Build
      working-directory: ./formula1_service
      run: npm run build
