name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'formula1_frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'formula1_frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: formula1_frontend/package-lock.json

    - name: Install Dependencies
      working-directory: ./formula1_frontend
      run: npm ci

    - name: Build
      working-directory: ./formula1_frontend
      run: npm run build
