# .github/workflows/gitstream.yml
name: gitStream

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  gitstream:
    runs-on: ubuntu-latest
    name: gitStream workflow automation
    steps:
      - uses: linear-b/gitstream-github-action@v2
        id: rules-engine