name: gitStream workflow automation repo level

on:
  workflow_dispatch:
    inputs:
      client_payload:
        description: The Client payload
        required: true
      full_repository:
        description: the repository name include the owner in `owner/repo_name` format
        required: true
      head_ref:
        description: the head sha
        required: true
      base_ref:
        description: the base ref
        required: true
      installation_id:
        description: the installation id
        required: false
      resolver_url:
        description: the resolver url to pass results to
        required: true
      resolver_token:
        description: Optional resolver token for resolver service
        required: false
        default: ''

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  gitStream:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Adding PR Url
        shell: bash
        run: |
          set -euo pipefail

          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            repo="${GITHUB_REPOSITORY}"
            pr_number=$(jq -r '.pull_request.number' < "$GITHUB_EVENT_PATH")
            pr_url=$(jq -r '.pull_request.html_url' < "$GITHUB_EVENT_PATH")
            head_ref=$(jq -r '.pull_request.head.ref' < "$GITHUB_EVENT_PATH")
            author=$(jq -r '.pull_request.user.login' < "$GITHUB_EVENT_PATH")
            echo "[${repo}#${pr_number}](${pr_url}) - \`${head_ref}\` by ${author}" >> "$GITHUB_STEP_SUMMARY"
          else
            # workflow_dispatch: inputs.client_payload is expected to be a JSON string
            client_payload_raw=$(jq -r '.inputs.client_payload' < "$GITHUB_EVENT_PATH")
            repo=$(echo "$client_payload_raw" | jq -r '.repo')
            pr_number=$(echo "$client_payload_raw" | jq -r '.prContext.number')
            pr_url=$(echo "$client_payload_raw" | jq -r '.prContext.url')
            branch=$(echo "$client_payload_raw" | jq -r '.branch')
            author=$(echo "$client_payload_raw" | jq -r '.prContext.author')
            echo "[${repo}#${pr_number}](${pr_url}) - \`${branch}\` by ${author}" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Evaluate Rules
        uses: linear-b/gitstream-github-action@v2
        id: rules-engine
        with:
          full_repository: ${{ github.event.inputs.full_repository || github.repository }}
          head_ref: ${{ github.event.inputs.head_ref || github.head_ref }}
          base_ref: ${{ github.event.inputs.base_ref || github.base_ref }}
          client_payload: ${{ github.event.inputs.client_payload || '' }}
          installation_id: ${{ github.event.inputs.installation_id || '' }}
          resolver_url: ${{ github.event.inputs.resolver_url || '' }}
          resolver_token: ${{ github.event.inputs.resolver_token || '' }}
